Repository geophystech/eqalert.ru, pull requests merged in 2018-08, with the labels that each got.

#234 Update about project title
  src/components/StaticPage.vue
Labels: bug, content

#236 Make tables responsive
  src/components/Event.vue
  src/components/event/Buildings.vue
  src/components/event/GeneralInformation.vue
  src/components/event/LDOs.vue
  src/components/event/Settlements.vue
Labels: enhancement, layout

#235 Add correct copyrighter
  LICENSE
Labels: documentation

#237 Update footer link
  src/components/AppFooter.vue
Labels: layout

#239 Disable tile servers
  src/map_functions.js
  test/unit/specs/AppFooter.spec.js
Labels: enhancement, map

#241 Remove redundant js tags
  index.html
Labels: enhancement, map, performance, refactoring

#244 Update showing status of stations
  src/components/maps/Buildings.vue
  src/components/maps/GeneralInformation.vue
  src/components/maps/LDOs.vue
  src/components/maps/Settlements.vue
Labels: enhancement, map

#246 Add telegram icon to header
  src/components/AppHeader.vue
  test/unit/specs/AppHeader.spec.js
Labels: enhancement, layout

#248 Fix layout of analytics page
  src/components/Analytics.vue
Labels: charts, enhancement, layout

#254 Fix events header counters
  src/components/Events.vue
Labels: bug, components

#255 Fix layers disappered on exiting from fullscreen
  src/map_functions.js
Labels: bug, components

#256 Fix events duplications
  src/components/Events.vue
Labels: bug, components

#259 Fix analytic charts
  src/components/charts/ChartByDatetime.vue
  src/components/charts/ChartByDensityCounts.vue
  src/components/charts/ChartByMagnitudeCumulative.vue
  src/components/charts/ChartByRMSAllocation.vue
  src/components/charts/ChartByStationCounts.vue
  src/store/app.js
Labels: bug, charts

#261 Remove hardcoded magnitude values from chart Y-axios descriptions
  src/components/charts/ChartByRMSAllocation.vue
  src/components/charts/ChartByStationCounts.vue
Labels: charts, enhancement

#267 Prepare for release 2.0.0
  config/prod.env.js
  src/components/event/Header.vue
  src/components/maps/Mainpage.vue
Labels: components, map
